export const defaultExpense = {
  id: null,
  amount: 0,
  currency: 'EUR',
  inMainCurrency: 0,
  mainCurrency: 'EUR',
  category: null,
  tags: [],
  comment: null,
  date: null,
};

export const defaultSettings = {
  mainCurrency: 'EUR',
  faceID: false,
};

export const defaultCurrencies = {
  USD: {
    id: 'USD',
    name: 'US dollar',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  JPY: {
    id: 'JPY',
    name: 'Japanese yen',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  BGN: {
    id: 'BGN',
    name: 'Bulgarian lev',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  CZK: {
    id: 'CZK',
    name: 'Czech koruna',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  DKK: {
    id: 'DKK',
    name: 'Danish krone',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  GBP: {
    id: 'GBP',
    name: 'Pound sterling',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  HUF: {
    id: 'HUF',
    name: 'Hungarian forint',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  PLN: {
    id: 'PLN',
    name: 'Polish zloty',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  RON: {
    id: 'RON',
    name: 'Romanian leu',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  SEK: {
    id: 'SEK',
    name: 'Swedish krona',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  CHF: {
    id: 'CHF',
    name: 'Swiss franc',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  ISK: {
    id: 'ISK',
    name: 'Icelandic krona',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  NOK: {
    id: 'NOK',
    name: 'Norwegian krone',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  HRK: {
    id: 'HRK',
    name: 'Croatian kuna',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  RUB: {
    id: 'RUB',
    name: 'Russian rouble',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  TRY: {
    id: 'TRY',
    name: 'Turkish lira',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  AUD: {
    id: 'AUD',
    name: 'Australian dollar',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  BRL: {
    id: 'BRL',
    name: 'Brazilian real',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  CAD: {
    id: 'CAD',
    name: 'Canadian dollar',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  CNY: {
    id: 'CNY',
    name: 'Chinese yuan renminbi',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  HKD: {
    id: 'HKD',
    name: 'Hong Kong dollar',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  IDR: {
    id: 'IDR',
    name: 'Indonesian rupiah',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  ILS: {
    id: 'ILS',
    name: 'Israeli shekel',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  INR: {
    id: 'INR',
    name: 'Indian rupee',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  KRW: {
    id: 'KRW',
    name: 'South Korean won',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  MXN: {
    id: 'MXN',
    name: 'Mexican peso',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  MYR: {
    id: 'MYR',
    name: 'Malaysian ringgit',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  NZD: {
    id: 'NZD',
    name: 'New Zealand dollar',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  PHP: {
    id: 'PHP',
    name: 'Philippine peso',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  SGD: {
    id: 'SGD',
    name: 'Singapore dollar',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  THB: {
    id: 'THB',
    name: 'Thai baht',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
  ZAR: {
    id: 'ZAR',
    name: 'South African rand',
    symbol: '💸',
    fxRatePerEuro: 1,
  },
};
